### ISSUE TITLE
fatal: unable to access

### ISSUE THREAD

**Issue by vgevers** [githubschool/Sept-5#17]
GDI-foundation:Sept-5 neo$ git push
remote: Permission to githubschool/Sept-5.git denied to GDI-foundation.
fatal: unable to access 'https://github.com/githubschool/Sept-5.git/': The requested URL returned error: 403
GDI-foundation:Sept-5 neo$

**Comment by githubteacher** [comment]
@vgevers maybe this could help https://stackoverflow.com/questions/15381198/remove-credentials-from-git

**Comment by vgevers** [comment]
I'm not sure how to erase through the command line, but it's fairly easily to do it through the Keychain Access app. Just go to Applications -> Utilties -> Keychain Access, then enter "github.com". You can either delete the invalid item or update the password from with the app.
